---
# maintains ports, bianry or repo urls

org: encapsulate
domain_regex: ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
monitor_server_dns: monitor.encapsulate.xyz
ansible_port: 8192

architecture_map:
  x86_64: amd64
  aarch64: arm64

tmp_dir: /tmp

rust:
  root: /opt
  path: /opt/cargo

default_node_types:
  - validator
  - default

cometbft:
  source_url: https://github.com/heliaxdev/cometbft/releases/download
  file_extension: tar.gz

namada:
  source_url: https://github.com/anoma/namada
  validator:   
    ports:
      p2p_port: 20556
      proxy_port: 20558
      rpc_port: 20557
      prometheus_port: 20560
      ethereum_rpc_port: 20545
  fullnode:   
    ports:
      p2p_port: 20656
      proxy_port: 20658
      rpc_port: 20657
      prometheus_port: 20660
      ethereum_rpc_port: 20645
