---
# maintains ports, bianry or repo urls

org: encapsulate
domain_regex: ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
monitor_server_dns: monitor.encapsulate.xyz
ansible_port: 8192

architecture_map:
  x86_64: amd64
  aarch64: arm64
tmp_dir: /tmp

default_node_types:
  - validator
  - default

cometbft:
  source_url: https://github.com/cometbft/cometbft/releases/download
  file_extension: tar.gz

namada:
  source_url: https://github.com/anoma/namada/releases/download
  file_extension: tar.gz
  validator:   
    ports:
      p2p_port: 26656
      proxy_port: 26658
      rpc_port: 26657
      prometheus_port: 26660
