---
# maintains file name, binary names, and anything which is not a directory or path

# config file names
node_config_file_name: config.toml

node_node_key_file_name: node_key.json
node_priv_validator_key_file_name: priv_validator_key.json

node_wallet_file_name: wallet.toml

node_migration_script_file_name: pre_phase4_migration.json

# binary names
node_binaries:
  namada_default:
    default_binary_name: "namada"
    dest_binary_name: "{{ service_identifier }}"
  namada_node:
    default_binary_name: "namadan"
    dest_binary_name: "namadan"
  namada_client:
    default_binary_name: "namadac"
    dest_binary_name: "namadac"
  namada_worker:
    default_binary_name: "namadaw"
    dest_binary_name: "namadaw"
  cometbft_default:
    default_binary_name: "cometbft"
    dest_binary_name: "cometbft"

node_environment_general_file_name: "{{ service_identifier }}.env"

node_space_optimization_settings:
  indexer: "null"

node_type_settings:
  proxy_app:
    address:
      default: tcp://127.0.0.1
  rpc:
    address:
      validator: tcp://127.0.0.1
      fullnode: tcp://0.0.0.0
  p2p:
    address:
      default: tcp://0.0.0.0
  double_sign_check_height:
    validator: 10
    fullnode: 0
  ethereum_rpc:
    address:
      validator: http://127.0.0.1
      fullnode: http://0.0.0.0

########################################################################################################################
# SENTRY CONFIGURATION: change only if you wanna run validator in a sentry architecture
########################################################################################################################
# pex:
#   validator:
#     value: false
#     explanation: Disables peer exchange to keep the validator private and prevent gossiping with the network.
#                  Validator only communicates with its sentry nodes.
#   fullnode:
#     value: true
#     explanation: Enables peer exchange so the sentry node can connect with public peers and discover other nodes.

# persistent_peers:
#   validator:
#     value: List of sentry nodes
#     explanation: Ensures stable connections between the validator and its sentry nodes. No other peer should be added other than your own sentry nodes
#   fullnode:
#     value: Validator node and other sentry nodes
#     explanation: Sentry nodes maintain connections with the validator and optionally other sentries for redundancy.

# private_peer_ids:
#   validator:
#     value: None ("")
#     explanation: Validators do not need to hide who they are communicating with, as they only connect with trusted sentries.
#   fullnode:
#     value: Validator node ID
#     explanation: Marks the validator as a private peer to ensure the validator's IP is not gossiped to the network.

# unconditional_peer_ids:
#   validator:
#     value: Optionally sentry node IDs
#     explanation: Ensures that critical sentry nodes are always connected, even with inbound/outbound limits.
#   fullnode:
#     value: Validator node ID and optionally other sentries
#     explanation: Guarantees continuous connection with the validator, maintaining stability even under restrictions.

# addr_book_strict:
#   validator:
#     value: false
#     explanation: Allows connections from non-routable IPs for private or local communication.
#   fullnode:
#     value: false
#     explanation: Enables connections from non-routable IPs, useful in private network setups.

# seeds:
#   validator:
#     value: None ("")
#     explanation: Validators do not need to connect to seed nodes since they only communicate with sentry nodes.
#   fullnode:
#     value: "can connect to other seeds"
#     explanation: Fullnodes (sentry nodes) can connect to seed nodes to discover peers and maintain connectivity with the network.

########################################################################################################################
# Uncomment below settings to toggle node sentry settings
########################################################################################################################

# node_sentry_settings:
#   pex:
#     validator: # false
#     fullnode: # true
#   persistent_peers:
#     validator: # list of sentry nodes
#     fullnode: # validator node, optionally other sentry nodes
#   private_peer_ids:
#     validator: # ""
#     fullnode: # validator node ID
#   unconditional_peer_ids:
#     validator: # sentry node IDs (optional)
#     fullnode: # validator node ID and sentry node IDs (optional)
#   addr_book_strict:
#     validator: # false
#     fullnode: # false
#   seeds:
#     validator: # ""
#     fullnode: # can connect to other seeds
#   external_address:
#     validator: # ""
#     fullnode: # can use the default if its a fullnode
