---
# maintains mainnet inventory grouped by project names
all:
  vars:
    env: mainnet
  children:
    namada:
      hosts:
        validator.namada.mainnet.encapsulate.xyz:
          type: validator
