---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: testnet
  children:
    namada:
      hosts:
        validator.namada.testnet.encapsulate.xyz:
          type: validator
