---
- name: Create a directory with specific permissions and ownership
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ service_identifier }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Download and unarchive the binary
  ansible.builtin.unarchive:
    src: "{{ source_url }}/{{ suffix_url }}"
    dest: "{{ tmp_dir }}/{{ service_identifier }}"
    remote_src: true
    owner: root
    group: root
    mode: "0755"

- name: Copy the binary file
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/{{ service_identifier }}/{{ item }}"
    dest: "{{ binary_dest_path }}"
    remote_src: true
    owner: root
    group: root
    force: true
    mode: "0755"
  loop: "{{ extracted_path }}"
  notify: 
    - Restart service

- name: Clean up the temporary files in /tmp
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ service_identifier }}"
    state: absent
