---
# maintains directories and paths
node_home_dir: /opt/{{ service_identifier }}

node_bin_dir: "{{ node_home_dir }}/bin"
node_config_dir: "{{ node_home_dir }}/config"
node_network_dir: "{{ node_config_dir }}/{{ namada[type].chain_id }}"
node_data_dir: "{{ node_home_dir }}/data"
node_wasm_dir: "{{ node_home_dir }}/wasm"
node_cometbft_dir: "{{ node_home_dir }}/cometbft"
node_env_dir: "{{ node_home_dir }}/environment"
node_log_dir: "{{ node_home_dir }}/log"

node_cometbft_config_dir: "{{ node_cometbft_dir }}/config"
node_cometbft_data_dir: "{{ node_cometbft_dir }}/data"

node_directories:
  - "{{ node_home_dir }}"
  - "{{ node_bin_dir }}"
  - "{{ node_config_dir }}"
  - "{{ node_data_dir }}"
  - "{{ node_cometbft_dir }}"
  - "{{ node_env_dir }}"
  - "{{ node_log_dir }}"
  - "{{ node_cometbft_config_dir }}"
  - "{{ node_cometbft_data_dir }}"

node_log_file_path: "{{ node_log_dir }}/{{ service_identifier }}.log"

node_config_file_path: "{{ node_network_dir }}/{{ node_config_file_name }}"

node_environment_general_file_path: "{{ node_env_dir }}/{{ node_environment_general_file_name }}"

node_priv_validator_key_path: "{{ node_cometbft_config_dir }}/{{ node_priv_validator_key_file_name }}"
node_node_key_path: "{{ node_cometbft_config_dir }}/{{ node_node_key_file_name }}"

node_wallet_file_path: "{{ node_network_dir }}/{{ node_wallet_file_name }}"

node_migration_script_file_path: "{{ node_config_dir }}/{{ node_migration_script_file_name }}"
